'use client';

import React from 'react';
import { PageHeader } from '@/components/admin/PageHeader';
import { MonitorPlay, LayoutTemplate, ToggleLeft, ToggleRight, Info } from 'lucide-react';
import { cn } from '@/lib/utils';

export default function StudentDashboardManagerPage() {
  const widgets = [
    { id: 'w1', name: 'Continue Learning Card', description: 'Prominent card showing the next incomplete lesson.', active: true, required: true },
    { id: 'w2', name: 'Learning Streak Tracker', description: 'Gamification widget showing consecutive days learned.', active: true, required: false },
    { id: 'w3', name: 'AI Mentor Insights', description: 'Personalized recommendations generated by Gemini.', active: true, required: false },
    { id: 'w4', name: 'Community Discussions', description: 'Recent forum activity related to the current phase.', active: false, required: false },
    { id: 'w5', name: 'Upcoming Webinars', description: 'Live sessions scheduled by the instructor.', active: false, required: false },
  ];

  return (
    <div className="space-y-8 max-w-5xl">
      <PageHeader 
        title="Student Dashboard Layout" 
        description="Configure which widgets and tools appear on the student's primary dashboard."
        actions={
          <button className="inline-flex items-center gap-2 rounded-xl bg-brand px-4 py-2 text-sm font-semibold text-white transition-all hover:bg-brand/90 shadow-[0_0_15px_rgba(255,107,53,0.3)]">
            Save Configuration
          </button>
        }
      />
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Available Widgets List */}
        <div className="lg:col-span-2 space-y-6">
          <div className="flex items-center gap-2 px-2 text-sm font-medium text-slate-400 uppercase tracking-wider mb-2">
            <LayoutTemplate className="h-4 w-4" />
            Dashboard Widgets
          </div>

          <div className="space-y-4">
            {widgets.map((widget) => (
              <div 
                key={widget.id} 
                className={cn(
                  "p-5 rounded-2xl border transition-all",
                  widget.active 
                    ? "border-brand/30 bg-brand/5 shadow-[0_0_20px_rgba(255,107,53,0.05)]" 
                    : "border-white/5 bg-[#121214]/80 backdrop-blur-sm"
                )}
              >
                <div className="flex items-start justify-between">
                  <div>
                    <div className="flex items-center gap-2">
                      <h4 className="text-base font-semibold text-slate-200">{widget.name}</h4>
                      {widget.required && (
                        <span className="px-2 py-0.5 rounded text-[10px] uppercase font-bold bg-white/10 text-slate-400">Required</span>
                      )}
                    </div>
                    <p className="text-sm text-muted-foreground mt-1.5">{widget.description}</p>
                  </div>
                  
                  <button 
                    disabled={widget.required}
                    className={cn(
                      "transition-colors",
                      widget.required ? "opacity-50 cursor-not-allowed" : "cursor-pointer"
                    )}
                  >
                    {widget.active ? (
                      <ToggleRight className="h-8 w-8 text-brand" />
                    ) : (
                      <ToggleLeft className="h-8 w-8 text-muted-foreground" />
                    )}
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Layout Preview Wireframe */}
        <div className="w-full">
          <div className="sticky top-24 rounded-2xl border border-white/5 bg-[#121214]/50 p-6 backdrop-blur-sm">
            <h3 className="text-sm font-medium text-white mb-6 flex items-center gap-2">
              <MonitorPlay className="h-4 w-4 text-brand" />
              Layout Preview
            </h3>
            
            <div className="aspect-[4/3] w-full rounded-xl border border-white/10 bg-[#0A0A0A] p-4 flex flex-col gap-3 opacity-80">
              {/* Fake Header */}
              <div className="h-6 w-full rounded-md bg-white/5 flex items-center justify-between px-2">
                 <div className="h-2 w-16 bg-white/10 rounded" />
                 <div className="h-4 w-4 rounded-full bg-brand/20" />
              </div>
              
              {/* Fake Main Content */}
              <div className="flex-1 flex gap-3">
                <div className="flex-1 flex flex-col gap-3">
                  <div className="h-24 w-full rounded-lg bg-brand/10 border border-brand/20 flex flex-col justify-end p-2">
                    <div className="h-2 w-3/4 bg-brand/30 rounded mb-1" />
                    <div className="h-2 w-1/2 bg-brand/30 rounded" />
                  </div>
                  <div className="h-16 w-full rounded-lg bg-white/5" />
                </div>
                <div className="w-1/3 flex flex-col gap-3">
                  <div className="h-16 w-full rounded-lg bg-white/5" />
                  <div className="flex-1 w-full rounded-lg bg-white/5" />
                </div>
              </div>
            </div>

            <div className="mt-6 flex items-start gap-3 p-3 rounded-lg bg-blue-500/10 border border-blue-500/20">
              <Info className="h-4 w-4 text-blue-400 shrink-0 mt-0.5" />
              <p className="text-xs text-blue-200/70 leading-relaxed">
                Changes to widget visibility affect all student accounts immediately. Required widgets cannot be disabled to ensure core platform functionality.
              </p>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
